### ISSUE TITLE
Expose current tag for ease of writing update scripts 

### ISSUE THREAD

**Issue by LizzyTrickster** [Forecaster/ForeModpacker#27]
Original put on discord 

Having the current version tag exposed at a publicly viewable address (I.e. Railcraftpack/current) would allow for update notifiers/updates to be made for stuff like MultiMC which can run arbitrary code pre-launch.

~~Also having the current tag version in the archive will allow for easier checking~~ #28

**Comment by Forecaster** [comment]
This will also require a special endpoint to request generating the archive (if needed) and pass the ~~file to the script~~ url to the archive in the reply.

It's also going to have to check the patron status if the requester is a patron since it bypasses the regular login.
