### ISSUE TITLE
API Auth Key

### ISSUE THREAD

**Issue by LizzyTrickster** [Forecaster/ForeModpacker#29]
We need some way to authenticate users when downloading the pack via automated scripts (i.e. for updater scripts). This key should be able to be generated on the platform after the user has logged in with either Patreon or Google.

Perhaps also some way to check if the API key of a user is still pledged at the required level and return an error code if not? Would require storing of some more stuff from the Patreon API should it allow for that.

**Comment by Forecaster** [comment]
This is done!
